<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{

    public  function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub

    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function replies(){
        return $this->hasMany(Reply::class);
    }

    public  function  category(){
        return $this->belongsTo(Category::class);
    }

    public function getPathAttribute(){
        return asset("/api/questions/$this->slug");
    }
}
